-d D:\github\HRA_product\TangCartMSX\RTL\Tang20kcartMSX\impl\gwsynthesis\Tang20kcartMSX.vg
-p GW2AR-18-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst D:\github\HRA_product\TangCartMSX\RTL\Tang20kcartMSX\src\Tang20kcartMSX.cst
-cfg D:\github\HRA_product\TangCartMSX\RTL\Tang20kcartMSX\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
