onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb/u_dut/u_v9958/CLK
add wave -noupdate /tb/u_dut/u_v9958/RESET
add wave -noupdate /tb/u_dut/u_v9958/INITIAL_BUSY
add wave -noupdate /tb/u_dut/u_v9958/REQ
add wave -noupdate /tb/u_dut/u_v9958/ACK
add wave -noupdate /tb/u_dut/u_v9958/WRT
add wave -noupdate /tb/u_dut/u_v9958/ADR
add wave -noupdate /tb/u_dut/u_v9958/DBI
add wave -noupdate -radix ascii /tb/u_dut/u_v9958/DBO
add wave -noupdate /tb/u_dut/u_v9958/INT_N
add wave -noupdate /tb/u_dut/u_v9958/PRAMOE_N
add wave -noupdate /tb/u_dut/u_v9958/PRAMWE_N
add wave -noupdate /tb/u_dut/u_v9958/PRAMADR
add wave -noupdate /tb/u_dut/u_v9958/PRAMDBI
add wave -noupdate /tb/u_dut/u_v9958/PRAMDBO
add wave -noupdate /tb/u_dut/u_v9958/VDPSPEEDMODE
add wave -noupdate /tb/u_dut/u_v9958/RATIOMODE
add wave -noupdate /tb/u_dut/u_v9958/CENTERYJK_R25_N
add wave -noupdate /tb/u_dut/u_v9958/PVIDEO_CLK
add wave -noupdate /tb/u_dut/u_v9958/PVIDEO_DATA_EN
add wave -noupdate -format Analog-Step -height 64 -max 63.0 -radix unsigned /tb/u_dut/u_v9958/PVIDEOR
add wave -noupdate -format Analog-Step -height 64 -max 63.0 -radix unsigned /tb/u_dut/u_v9958/PVIDEOG
add wave -noupdate -format Analog-Step -height 64 -max 63.0 -radix unsigned /tb/u_dut/u_v9958/PVIDEOB
add wave -noupdate /tb/u_dut/u_v9958/PVIDEOHS_N
add wave -noupdate /tb/u_dut/u_v9958/PVIDEOVS_N
add wave -noupdate /tb/u_dut/u_v9958/PVIDEOCS_N
add wave -noupdate /tb/u_dut/u_v9958/PVIDEODHCLK
add wave -noupdate /tb/u_dut/u_v9958/PVIDEODLCLK
add wave -noupdate /tb/u_dut/u_v9958/DISPRESO
add wave -noupdate /tb/u_dut/u_v9958/NTSC_PAL_TYPE
add wave -noupdate /tb/u_dut/u_v9958/FORCED_V_MODE
add wave -noupdate /tb/u_dut/u_v9958/LEGACY_VGA
add wave -noupdate /tb/u_dut/u_v9958/VDP_ID
add wave -noupdate /tb/u_dut/u_v9958/OFFSET_Y
add wave -noupdate /tb/u_dut/u_v9958/ENABLE
add wave -noupdate /tb/u_dut/u_v9958/FF_ENABLE_CNT
add wave -noupdate /tb/u_dut/u_v9958/H_CNT
add wave -noupdate /tb/u_dut/u_v9958/V_CNT
add wave -noupdate /tb/u_dut/u_v9958/DOTSTATE
add wave -noupdate /tb/u_dut/u_v9958/EIGHTDOTSTATE
add wave -noupdate /tb/u_dut/u_v9958/FIELD
add wave -noupdate /tb/u_dut/u_v9958/HD
add wave -noupdate /tb/u_dut/u_v9958/VD
add wave -noupdate /tb/u_dut/u_v9958/ACTIVE_LINE
add wave -noupdate /tb/u_dut/u_v9958/V_BLANKING_START
add wave -noupdate /tb/u_dut/u_v9958/VSYNCINT_N
add wave -noupdate /tb/u_dut/u_v9958/CLR_VSYNC_INT
add wave -noupdate /tb/u_dut/u_v9958/REQ_VSYNC_INT_N
add wave -noupdate /tb/u_dut/u_v9958/HSYNCINT_N
add wave -noupdate /tb/u_dut/u_v9958/CLR_HSYNC_INT
add wave -noupdate /tb/u_dut/u_v9958/REQ_HSYNC_INT_N
add wave -noupdate /tb/u_dut/u_v9958/WINDOW
add wave -noupdate /tb/u_dut/u_v9958/WINDOW_X
add wave -noupdate /tb/u_dut/u_v9958/PREWINDOW_X
add wave -noupdate /tb/u_dut/u_v9958/PREWINDOW_Y
add wave -noupdate /tb/u_dut/u_v9958/PREWINDOW_Y_SP
add wave -noupdate /tb/u_dut/u_v9958/PREWINDOW
add wave -noupdate /tb/u_dut/u_v9958/BWINDOW_X
add wave -noupdate /tb/u_dut/u_v9958/BWINDOW_Y
add wave -noupdate /tb/u_dut/u_v9958/BWINDOW
add wave -noupdate /tb/u_dut/u_v9958/PREDOTCOUNTER_X
add wave -noupdate /tb/u_dut/u_v9958/PREDOTCOUNTER_Y
add wave -noupdate /tb/u_dut/u_v9958/PREDOTCOUNTER_YP
add wave -noupdate /tb/u_dut/u_v9958/VDPVRAMACCESSADDR
add wave -noupdate /tb/u_dut/u_v9958/DISPMODEVGA
add wave -noupdate /tb/u_dut/u_v9958/VDPVRAMREADINGR
add wave -noupdate /tb/u_dut/u_v9958/VDPVRAMREADINGA
add wave -noupdate /tb/u_dut/u_v9958/VDPR0DISPNUM
add wave -noupdate /tb/u_dut/u_v9958/VDPVRAMACCESSDATA
add wave -noupdate /tb/u_dut/u_v9958/VDPVRAMACCESSADDRTMP
add wave -noupdate /tb/u_dut/u_v9958/VDPVRAMADDRSETREQ
add wave -noupdate /tb/u_dut/u_v9958/VDPVRAMADDRSETACK
add wave -noupdate /tb/u_dut/u_v9958/VDPVRAMWRREQ
add wave -noupdate /tb/u_dut/u_v9958/VDPVRAMWRACK
add wave -noupdate /tb/u_dut/u_v9958/VDPVRAMRDDATA
add wave -noupdate /tb/u_dut/u_v9958/W_VRAM_RD_REQ
add wave -noupdate /tb/u_dut/u_v9958/FF_VRAM_RD_ACK
add wave -noupdate /tb/u_dut/u_v9958/W_R9_PAL_MODE
add wave -noupdate /tb/u_dut/u_v9958/REG_R0_HSYNC_INT_EN
add wave -noupdate /tb/u_dut/u_v9958/REG_R1_SP_SIZE
add wave -noupdate /tb/u_dut/u_v9958/REG_R1_SP_ZOOM
add wave -noupdate /tb/u_dut/u_v9958/REG_R1_BL_CLKS
add wave -noupdate /tb/u_dut/u_v9958/REG_R1_VSYNC_INT_EN
add wave -noupdate /tb/u_dut/u_v9958/REG_R1_DISP_ON
add wave -noupdate /tb/u_dut/u_v9958/REG_R2_PT_NAM_ADDR
add wave -noupdate /tb/u_dut/u_v9958/REG_R4_PT_GEN_ADDR
add wave -noupdate /tb/u_dut/u_v9958/REG_R10R3_COL_ADDR
add wave -noupdate /tb/u_dut/u_v9958/REG_R11R5_SP_ATR_ADDR
add wave -noupdate /tb/u_dut/u_v9958/REG_R6_SP_GEN_ADDR
add wave -noupdate /tb/u_dut/u_v9958/REG_R7_FRAME_COL
add wave -noupdate /tb/u_dut/u_v9958/REG_R8_SP_OFF
add wave -noupdate /tb/u_dut/u_v9958/REG_R8_COL0_ON
add wave -noupdate /tb/u_dut/u_v9958/REG_R9_PAL_MODE
add wave -noupdate /tb/u_dut/u_v9958/REG_R9_INTERLACE_MODE
add wave -noupdate /tb/u_dut/u_v9958/REG_R9_Y_DOTS
add wave -noupdate /tb/u_dut/u_v9958/REG_R12_BLINK_MODE
add wave -noupdate /tb/u_dut/u_v9958/REG_R13_BLINK_PERIOD
add wave -noupdate /tb/u_dut/u_v9958/REG_R18_ADJ
add wave -noupdate /tb/u_dut/u_v9958/REG_R19_HSYNC_INT_LINE
add wave -noupdate /tb/u_dut/u_v9958/REG_R23_VSTART_LINE
add wave -noupdate /tb/u_dut/u_v9958/REG_R25_CMD
add wave -noupdate /tb/u_dut/u_v9958/REG_R25_YAE
add wave -noupdate /tb/u_dut/u_v9958/REG_R25_YJK
add wave -noupdate /tb/u_dut/u_v9958/REG_R25_MSK
add wave -noupdate /tb/u_dut/u_v9958/REG_R25_SP2
add wave -noupdate /tb/u_dut/u_v9958/REG_R26_H_SCROLL
add wave -noupdate /tb/u_dut/u_v9958/REG_R27_H_SCROLL
add wave -noupdate /tb/u_dut/u_v9958/TEXT_MODE
add wave -noupdate /tb/u_dut/u_v9958/VDPMODETEXT1
add wave -noupdate /tb/u_dut/u_v9958/VDPMODETEXT1Q
add wave -noupdate /tb/u_dut/u_v9958/VDPMODETEXT2
add wave -noupdate /tb/u_dut/u_v9958/VDPMODEMULTI
add wave -noupdate /tb/u_dut/u_v9958/VDPMODEMULTIQ
add wave -noupdate /tb/u_dut/u_v9958/VDPMODEGRAPHIC1
add wave -noupdate /tb/u_dut/u_v9958/VDPMODEGRAPHIC2
add wave -noupdate /tb/u_dut/u_v9958/VDPMODEGRAPHIC3
add wave -noupdate /tb/u_dut/u_v9958/VDPMODEGRAPHIC4
add wave -noupdate /tb/u_dut/u_v9958/VDPMODEGRAPHIC5
add wave -noupdate /tb/u_dut/u_v9958/VDPMODEGRAPHIC6
add wave -noupdate /tb/u_dut/u_v9958/VDPMODEGRAPHIC7
add wave -noupdate /tb/u_dut/u_v9958/VDPMODEISHIGHRES
add wave -noupdate /tb/u_dut/u_v9958/VDPMODEISVRAMINTERLEAVE
add wave -noupdate /tb/u_dut/u_v9958/PRAMADRT12
add wave -noupdate /tb/u_dut/u_v9958/COLORCODET12
add wave -noupdate /tb/u_dut/u_v9958/TXVRAMREADEN
add wave -noupdate /tb/u_dut/u_v9958/PRAMADRG123M
add wave -noupdate /tb/u_dut/u_v9958/COLORCODEG123M
add wave -noupdate /tb/u_dut/u_v9958/PRAMADRG4567
add wave -noupdate /tb/u_dut/u_v9958/COLORCODEG4567
add wave -noupdate /tb/u_dut/u_v9958/YJK_R
add wave -noupdate /tb/u_dut/u_v9958/YJK_G
add wave -noupdate /tb/u_dut/u_v9958/YJK_B
add wave -noupdate /tb/u_dut/u_v9958/YJK_EN
add wave -noupdate /tb/u_dut/u_v9958/SPMODE2
add wave -noupdate /tb/u_dut/u_v9958/SPVRAMACCESSING
add wave -noupdate /tb/u_dut/u_v9958/PRAMADRSPRITE
add wave -noupdate /tb/u_dut/u_v9958/SPRITECOLOROUT
add wave -noupdate /tb/u_dut/u_v9958/COLORCODESPRITE
add wave -noupdate /tb/u_dut/u_v9958/VDPS0SPCOLLISIONINCIDENCE
add wave -noupdate /tb/u_dut/u_v9958/VDPS0SPOVERMAPPED
add wave -noupdate /tb/u_dut/u_v9958/VDPS0SPOVERMAPPEDNUM
add wave -noupdate /tb/u_dut/u_v9958/VDPS3S4SPCOLLISIONX
add wave -noupdate /tb/u_dut/u_v9958/VDPS5S6SPCOLLISIONY
add wave -noupdate /tb/u_dut/u_v9958/SPVDPS0RESETREQ
add wave -noupdate /tb/u_dut/u_v9958/SPVDPS0RESETACK
add wave -noupdate /tb/u_dut/u_v9958/SPVDPS5RESETREQ
add wave -noupdate /tb/u_dut/u_v9958/SPVDPS5RESETACK
add wave -noupdate /tb/u_dut/u_v9958/PALETTEADDR_OUT
add wave -noupdate /tb/u_dut/u_v9958/PALETTEDATARB_OUT
add wave -noupdate /tb/u_dut/u_v9958/PALETTEDATAG_OUT
add wave -noupdate /tb/u_dut/u_v9958/VDPCMDCLR
add wave -noupdate /tb/u_dut/u_v9958/VDPCMDCE
add wave -noupdate /tb/u_dut/u_v9958/VDPCMDBD
add wave -noupdate /tb/u_dut/u_v9958/VDPCMDTR
add wave -noupdate /tb/u_dut/u_v9958/VDPCMDSXTMP
add wave -noupdate /tb/u_dut/u_v9958/VDPCMDREGNUM
add wave -noupdate /tb/u_dut/u_v9958/VDPCMDREGDATA
add wave -noupdate /tb/u_dut/u_v9958/VDPCMDREGWRACK
add wave -noupdate /tb/u_dut/u_v9958/VDPCMDTRCLRACK
add wave -noupdate /tb/u_dut/u_v9958/VDPCMDVRAMWRACK
add wave -noupdate /tb/u_dut/u_v9958/VDPCMDVRAMRDACK
add wave -noupdate /tb/u_dut/u_v9958/VDPCMDVRAMREADINGR
add wave -noupdate /tb/u_dut/u_v9958/VDPCMDVRAMREADINGA
add wave -noupdate /tb/u_dut/u_v9958/VDPCMDVRAMRDDATA
add wave -noupdate /tb/u_dut/u_v9958/VDPCMDREGWRREQ
add wave -noupdate /tb/u_dut/u_v9958/VDPCMDTRCLRREQ
add wave -noupdate /tb/u_dut/u_v9958/VDPCMDVRAMWRREQ
add wave -noupdate /tb/u_dut/u_v9958/VDPCMDVRAMRDREQ
add wave -noupdate /tb/u_dut/u_v9958/VDPCMDVRAMACCESSADDR
add wave -noupdate /tb/u_dut/u_v9958/VDPCMDVRAMWRDATA
add wave -noupdate /tb/u_dut/u_v9958/VDP_COMMAND_DRIVE
add wave -noupdate /tb/u_dut/u_v9958/VDP_COMMAND_ACTIVE
add wave -noupdate /tb/u_dut/u_v9958/CUR_VDP_COMMAND
add wave -noupdate /tb/u_dut/u_v9958/IVIDEOR
add wave -noupdate /tb/u_dut/u_v9958/IVIDEOG
add wave -noupdate /tb/u_dut/u_v9958/IVIDEOB
add wave -noupdate /tb/u_dut/u_v9958/IVIDEOR_VDP
add wave -noupdate /tb/u_dut/u_v9958/IVIDEOG_VDP
add wave -noupdate /tb/u_dut/u_v9958/IVIDEOB_VDP
add wave -noupdate /tb/u_dut/u_v9958/IVIDEOVS_N
add wave -noupdate /tb/u_dut/u_v9958/IVIDEOR_NTSC_PAL
add wave -noupdate /tb/u_dut/u_v9958/IVIDEOG_NTSC_PAL
add wave -noupdate /tb/u_dut/u_v9958/IVIDEOB_NTSC_PAL
add wave -noupdate /tb/u_dut/u_v9958/IVIDEOHS_N_NTSC_PAL
add wave -noupdate /tb/u_dut/u_v9958/IVIDEOVS_N_NTSC_PAL
add wave -noupdate /tb/u_dut/u_v9958/IVIDEOR_VGA
add wave -noupdate /tb/u_dut/u_v9958/IVIDEOG_VGA
add wave -noupdate /tb/u_dut/u_v9958/IVIDEOB_VGA
add wave -noupdate /tb/u_dut/u_v9958/IVIDEOHS_N_VGA
add wave -noupdate /tb/u_dut/u_v9958/IVIDEOVS_N_VGA
add wave -noupdate /tb/u_dut/u_v9958/IRAMADR
add wave -noupdate /tb/u_dut/u_v9958/PRAMDAT
add wave -noupdate /tb/u_dut/u_v9958/XRAMSEL
add wave -noupdate /tb/u_dut/u_v9958/PRAMDATPAIR
add wave -noupdate /tb/u_dut/u_v9958/HSYNC
add wave -noupdate /tb/u_dut/u_v9958/ENAHSYNC
add wave -noupdate /tb/u_dut/u_v9958/FF_INITIAL_BUSY
add wave -noupdate /tb/u_dut/u_v9958/FF_REQ
add wave -noupdate /tb/u_dut/u_v9958/FF_WRT
add wave -noupdate /tb/u_dut/u_v9958/W_ACK
add wave -noupdate /tb/u_dut/u_v9958/FF_PRAMOE_N_DL
add wave -noupdate /tb/u_dut/u_v9958/FF_PRAMWE_N_DL
add wave -noupdate /tb/u_dut/u_v9958/FF_PRAMOE_N
add wave -noupdate /tb/u_dut/u_v9958/FF_PRAMWE_N
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {66612191250 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 206
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 2
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {72263874360 ps} {72634471700 ps}
