-d D:\github\HRA_product\TangCartMSX\RTL\PSRAM_Test\impl\gwsynthesis\TangcartMSX.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst D:\github\HRA_product\TangCartMSX\RTL\PSRAM_Test\src\TangcartMSX.cst
-cfg D:\github\HRA_product\TangCartMSX\RTL\PSRAM_Test\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
