-d D:\github\HRA_product\TangCartMSX\RTL\tangconsole_step1\impl\gwsynthesis\tangconsole_step1.vg
-p GW5AT-60B-PBGA484A-1
-pn GW5AT-LV60PG484AC1/I0
-cst D:\github\HRA_product\TangCartMSX\RTL\tangconsole_step1\src\tangconsole.cst
-cfg D:\github\HRA_product\TangCartMSX\RTL\tangconsole_step1\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
