vlib work

vlog ..\ram\ip_ram.v
vlog ..\rom\ip_hello_world_rom.v
vlog ..\uart\ip_uart.v
vlog ..\uart\ip_uart_inst.v
vlog ..\..\modules\rtc\rtc.v
vlog ..\..\modules\ppi\ppi.v
vlog ..\..\modules\ppi\ppi_inst.v
vlog ..\..\modules\ssg\ssg.v
vlog ..\..\modules\secondary_slot\secondary_slot_inst.v
vlog ..\..\modules\i2s_audio\i2s_audio.v
vlog ..\..\modules\kanji_rom\kanji_rom.v
vlog ..\..\modules\megarom\megarom.v
vlog ..\..\modules\megarom\megarom_wo_scc.v
vlog ..\..\modules\megarom\scc\scc_channel_mixer.v
vlog ..\..\modules\megarom\scc\scc_channel_volume.v
vlog ..\..\modules\megarom\scc\scc_core.v
vlog ..\..\modules\megarom\scc\scc_inst.v
vlog ..\..\modules\megarom\scc\scc_ram.v
vlog ..\..\modules\megarom\scc\scc_register.v
vlog ..\..\modules\megarom\scc\scc_selector.v
vlog ..\..\modules\megarom\scc\scc_tone_generator_5ch.v
vlog ..\..\modules\memory_mapper\memory_mapper.v
vlog ..\..\modules\memory_mapper\memory_mapper_inst.v
vlog ..\..\modules\opll\ikaopll\IKAOPLL.v
vlog ..\..\modules\opll\ikaopll\IKAOPLL_modules\IKAOPLL_dac.v
vlog ..\..\modules\opll\ikaopll\IKAOPLL_modules\IKAOPLL_eg.v
vlog ..\..\modules\opll\ikaopll\IKAOPLL_modules\IKAOPLL_lfo.v
vlog ..\..\modules\opll\ikaopll\IKAOPLL_modules\IKAOPLL_op.v
vlog ..\..\modules\opll\ikaopll\IKAOPLL_modules\IKAOPLL_pg.v
vlog ..\..\modules\opll\ikaopll\IKAOPLL_modules\IKAOPLL_primitives.v
vlog ..\..\modules\opll\ikaopll\IKAOPLL_modules\IKAOPLL_reg.v
vlog ..\..\modules\opll\ikaopll\IKAOPLL_modules\IKAOPLL_timinggen.v
vlog ..\..\modules\opll\opll.v
vlog ..\..\modules\cz80\cz80_mcode.v
vlog ..\..\modules\cz80\cz80_reg.v
vlog ..\..\modules\cz80\cz80_alu.v
vlog ..\..\modules\cz80\cz80.v
vlog ..\..\modules\cz80\cz80_inst.v
vlog ..\..\modules\v9958\vdp.v
vlog ..\..\modules\v9958\vdp_color_bus.v
vlog ..\..\modules\v9958\vdp_color_decoder.v
vlog ..\..\modules\v9958\vdp_graphic123m.v
vlog ..\..\modules\v9958\vdp_graphic4567.v
vlog ..\..\modules\v9958\vdp_command.v
vlog ..\..\modules\v9958\vdp_inst.v
vlog ..\..\modules\v9958\vdp_interrupt.v
vlog ..\..\modules\v9958\vdp_ram_256byte.v
vlog ..\..\modules\v9958\vdp_ram_palette.v
vlog ..\..\modules\v9958\vdp_register.v
vlog ..\..\modules\v9958\vdp_spinforam.v
vlog ..\..\modules\v9958\vdp_sprite.v
vlog ..\..\modules\v9958\vdp_ssg.v
vlog ..\..\modules\v9958\vdp_text12.v
vlog ..\..\modules\v9958\vdp_wait_control.v
vlog ..\..\modules\sdram\ip_sdram_tangnano20k_cv.v
vlog ..\..\modules\micom_connect\micom_connect.v
vlog ..\..\modules\system_control\system_control.v
vlog ..\..\modules\video_out\video_out_hmag.v
vlog ..\..\modules\video_out\video_out_bilinear.v
vlog ..\..\modules\video_out\video_ram_line_buffer.v
vlog ..\..\modules\video_out\video_double_buffer.v
vlog ..\..\modules\video_out\video_out.v
vlog gowin_pll_dummy.v
vlog MT48LC2M32B2.v
vlog tangnano20k_step9.v
vlog tb.sv
pause
vsim -c -t 1ps -do run.do tb
move transcript log.txt
pause
