-d D:\github\HRA_product\TangCartMSX\RTL\tangnano_cartridge_t9\impl\gwsynthesis\TangcartMSX.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst D:\github\HRA_product\TangCartMSX\RTL\tangnano_cartridge_t9\src\TangcartMSX.cst
-cfg D:\github\HRA_product\TangCartMSX\RTL\tangnano_cartridge_t9\impl\pnr\device.cfg
-sdc D:\github\HRA_product\TangCartMSX\RTL\tangnano_cartridge_t9\src\TangcartMSX.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
