-d D:\github\HRA_product\TangCartMSX\RTL\tangprimer20k_uart_test\impl\gwsynthesis\tangprimer20k_step2.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst D:\github\HRA_product\TangCartMSX\RTL\tangprimer20k_uart_test\src\tangprimer20k_step2.cst
-cfg D:\github\HRA_product\TangCartMSX\RTL\tangprimer20k_uart_test\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
