-d /mnt/d/github/HRA_product/TangCartMSX/RTL/tangnano20k_hdmi_labo2/impl/gwsynthesis/tangnano20k_hdmi_labo.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst /mnt/d/github/HRA_product/TangCartMSX/RTL/tangnano20k_hdmi_labo2/src/tangnano20k_hdmi_labo.cst
-cfg /mnt/d/github/HRA_product/TangCartMSX/RTL/tangnano20k_hdmi_labo2/impl/pnr/device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
